inven/urls.py
from . import views
from django.urls import path

app_name = 'inventory'

urlpatterns = [
    path('add/', views.add, name='addProduct',), 
]

invenstory/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inventory/', include('inven.urls')),
    path('productlist/', include('productlist.urls')),
    path('inventory/', include('inven.urls')),
    path('', include('myinventory.urls')),
    path('sold/', include('terjual.urls')),
]

urlpatterns += staticfiles_urlpatterns()

myinventory/urls.py
from django.urls import path
from . import views

app_name = 'myinventory'

urlpatterns = [
    path('', views.inventory, name='inventory'),
]

productlist/urls.py
from django.urls import path
from . import views

app_name = 'productlist'

urlpatterns = [
    path('productlist', views.productlist, name='productlist'),
    ]

terjual/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'terjual'

urlpatterns = [
    path('', views.sold, name = 'sold'),
]

inven/models.py
from django.db import models

class Makanan(models.Model):
    makanan = models.CharField(max_length=100)
    class Meta:
        ordering = ('makanan',)
    def ambil(self):
        list_bahan_makanan = []
        bahanMakanan = BahanMakanan.objects.all()
        for i in bahanMakanan:
            if(self in i.makanan.all()):
                list_bahan_makanan.append(i)
        return list_bahan_makanan


class BahanMakanan(models.Model):
    bahan = models.CharField(max_length=100)
    jumlah = models.IntegerField()
    makanan = models.ManyToManyField(Makanan)

    class Meta:
        ordering = ('bahan',)
    

myinventory/models.py
from django.db import models
from inven.models import BahanMakanan

# Create your models here.
class NamaBarang(models.Model):
    namabahan = models.ForeignKey('inven.BahanMakanan', on_delete=models.CASCADE)
    jumlah = models.IntegerField()
#     tempat = models.CharField(max_length = 100, default = '')
#     kategori = models.CharField(max_length = 100, default = '')
#     hari = models.DateTimeField(default=datetime.now)
#     jam = models.TimeField(default = datetime.now)

# def __str__(self):
#     return "{}.{}".format(self.id, self.nama)

productlist/models.py
from django.db import models

# Create your models here.

terjual/models.py
from django.db import models
from inven.models import Makanan

# Create your models here.
class AddMakanan(models.Model):
    addmakanan = models.CharField(max_length=100)
    class Meta:
        ordering = ('addmakanan',)

    def __str__(self):
        return self.addmakanan

inven/forms.py
from . import models
from django import forms
from django.forms import formset_factory

class AddProduct(forms.Form):
    makanan = forms.CharField(label='Product Name', widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'type' : 'text',
    }), max_length=100)

class AddBahan(forms.Form):
    bahan = forms.CharField(label='Ingredients', widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'type' : 'text',
    }), max_length=100)
    jumlah = forms.IntegerField(label='Quantity', widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'type' : 'text',
    }))

Formset = formset_factory(AddBahan, extra=1)

myinventory/forms.py
from django import forms
from .models import NamaBarang

class Barang(forms.ModelForm):
    class Meta:
        model = NamaBarang
        

terjual/forms.py
from django import forms
from .models import AddMakanan


# class AddMakananForm(forms.ModelForm):
#     class Meta:
#         model = Jadwal
#         fields = ['category', 'activity', 'date', 'time', 'place']
#         widgets = {
#             'date': forms.DateInput(attrs={'type': 'date'}),
#             'time': forms.TimeInput(attrs={'type': 'time'})
#             }

#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         for field in self.Meta.fields:
#             self.fields[field].widget.attrs.update({
#                 'class': 'form-control'
#             })

inven/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Makanan, BahanMakanan
from .forms import AddProduct, Formset, AddBahan

def add(request):
    if request.method == 'GET':
        formset = Formset(request.GET or None)
        form = AddProduct()
    elif request.method == "POST" :
        form = AddProduct(request.POST)
        formset = Formset(request.POST)
        if formset.is_valid() and form.is_valid():
            mm = form.cleaned_data['makanan']
            if (Makanan.objects.filter(makanan=mm).count() == 0):
                mak = Makanan(
                    makanan = form.cleaned_data['makanan']
                )
                mak.save()
                i=0
                for form in formset:
                    ing = BahanMakanan(
                        bahan = form.cleaned_data.get('bahan'),
                        jumlah = form.cleaned_data.get('jumlah'),
                    )
                    ing.save()
                    ing.makanan.add(mak)
                    i+=1
            return redirect('inventory:addProduct')
    return render(request, 'inven/add.html', {'formset':formset, 'form':form })

invenstory/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    return render(request, 'home.html')

myinventory/views.py
from django.shortcuts import render

# Create your views here.
def inventory(request):
    return render(request, 'inventory.html')

productlist/views.py
from django.shortcuts import render
from inven.forms import AddProduct, AddBahan
from inven.models import Makanan, BahanMakanan


def productlist(request):
	makanan = Makanan.objects.all();
	bahanMakanan = BahanMakanan.objects.all();
	content = {'makanan' : makanan,
				'bahanMakanan' : bahanMakanan,
				}
	return render(request, 'productlist.html',content)

terjual/views.py
from django.shortcuts import render, redirect
from .models import AddMakanan
from inven.forms import AddProduct, AddBahan
from inven.models import Makanan
from . import forms

# Create your views here.

def sold(request):
    # makanan = Makanan.objects.all();
    # productTerjual = AddMakanan.objects.all();
    
    # content = {'makanan' : makanan, 'productTerjual' : productTerjual}

    return render(request, 'terjual/sold.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    {% block style %}{% endblock %}
    <title>Invenstory </title>

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">INVENSTORY</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="#">INVENTORY<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'inventory:addProduct' %}">ADD</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/sold">SOLD</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'productlist:productlist' %}">LIST</a>
                </li>
            </ul>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    {% block script %}{% endblock %}
</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<!-- ISIIN YAAA WKWKWK -->
{% endblock %}

templates/inven/add.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row m-5">
        <div class="control-group" id="fields">
            <h2 class="control-label" for="field1">Add Product</h2>
            <div class="controls">
                <form class="form-horizontal" method="POST" action="">
                    {% csrf_token %}
                    <div class="row spacer">
                        <div class="col-2">
                            <label>{{form.makanan.label}}</label>
                        </div>
                        <div class="col-4">
                            <div class="input-group">
                                {{form.makanan}}
                            </div>
                        </div>
                    </div>
                    {{ formset.management_form }}
                    {% for form in formset %}
                    <div class="row form-row spacer">
                        <div class="col-2">
                            <label>{{form.bahan.label}}</label>
                        </div>
                        <div class="col-4">
                            <div class="input-group">
                                {{form.bahan}}
                                <div class="input-group-append">
                                    <button type="button" class="btn btn-success add-form-row">+</button>
                                </div>
                            </div>
                        </div>
                        <div class="col-2">
                            <label>{{form.jumlah.label}}</label>
                        </div>
                        <div class="col-4">
                            <div class="input-group">
                                {{form.jumlah}}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <div class="row spacer">
                        <div class="col-4 offset-2">
                            <button type="submit" class="btn btn-block btn-primary m-2">Create</button>
                        </div>
                    </div>
                    <br>
                    <small>Press <span class="glyphicon glyphicon-plus gs"></span> to add another form field :)</small>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block script %}

<script type='text/javascript'>
    function updateElementIndex(el, prefix, ndx) {
        var id_regex = new RegExp('(' + prefix + '-\\d+)');
        var replacement = prefix + '-' + ndx;
        if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
        if (el.id) el.id = el.id.replace(id_regex, replacement);
        if (el.name) el.name = el.name.replace(id_regex, replacement);
    }
    function cloneMore(selector, prefix) {
        var newElement = $(selector).clone(true);
        var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
        newElement.find(':input:not([type=button]):not([type=submit]):not([type=reset])').each(function() {
            var name = $(this).attr('name').replace('-' + (total-1) + '-', '-' + total + '-');
            var id = 'id_' + name;
            $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
        });
        newElement.find('label').each(function() {
            var forValue = $(this).attr('for');
            if (forValue) {
              forValue = forValue.replace(('-' + (total-1) + '-'),( '-' + total + '-'));
              $(this).attr({'for': forValue});
            }
        });
        total++;
        $('#id_' + prefix + '-TOTAL_FORMS').val(total);
        $(selector).after(newElement);
        var conditionRow = $('.form-row:not(:last)');
        conditionRow.find('.btn.add-form-row')
        .removeClass('btn-success').addClass('btn-danger')
        .removeClass('add-form-row').addClass('remove-form-row')
        .html('<span class="glyphicon glyphicon-minus" aria-hidden="true"></span>');
        return false;
    }
    function deleteForm(prefix, btn) {
        var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
        if (total > 1){
            btn.closest('.form-row').remove();
            var forms = $('.form-row');
            $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
            for (var i=0, formCount=forms.length; i<formCount; i++) {
                $(forms.get(i)).find(':input').each(function() {
                    updateElementIndex(this, prefix, i);
                });
            }
        }
        return false;
    }
    $(document).on('click', '.add-form-row', function(e){
        e.preventDefault();
        cloneMore('.form-row:last', 'form');
        return false;
    });
    $(document).on('click', '.remove-form-row', function(e){
        e.preventDefault();
        deleteForm('form', $(this));
        return false;
    });
    </script>
{% endblock %}

templates/terjual/sold.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block style %} 
<link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}" media="screen">
{% endblock %}

{% block content %}


    <div class="row">
        <p class="sold-page">Products Sold</p>
    </div>

    {% for obj in makanan %}
    <div class="row">
        
        <div class="col-md-3">
            {{obj.makanan}}
        </div>

        <div class="col-md-3">
            <form class="css" action="{% url 'sold' %}" method="post">
            <button type="button" style="background-color: #892EFD" class = "btn btn-primary">Add</button>
            <input type="submit" class="btn btn-primary" value="Add">
        </div>

    </div>
    {% endfor %}

{% endblock %}